#!/bin/bash
#
#               __                             
#              /\ \__                          
#   __    _____\ \ ,_\ _____     __      ___   
# /'__`\ /\ '__`\ \ \//\ '__`\ /'__`\   /'___\ 
#/\ \L\.\\ \ \L\ \ \ \\ \ \L\ /\ \L\.\_/\ \__/ 
#\ \__/.\_\ \ ,__/\ \__\ \ ,__\ \__/.\_\ \____\
# \/__/\/_/\ \ \/  \/__/\ \ \/ \/__/\/_/\/____/
#           \ \_\        \ \_\                 
#            \/_/         \/_/    
# a pacman wrapper with syntax based on debian's apt
# (c) arcetera 2015 - wtfpl
# maintained by alefir

SYNTAX=$1
INPUT=$2

case $SYNTAX in
        install)        sudo pacman -S $INPUT;;
        search)         pacman -Ss $INPUT;;
        remove)         sudo pacman -Rs $INPUT;;
        upgrade)        sudo pacman -Syu;;
        update)         sudo padman -Sy;
                        echo "Run aptpac upgrade *immediately*. pacman does not support partial upgrades. running merely 'upgrade' would suffice. failure to do this could result in a broken installation.";;
        download)       sudo pacman -Sw $INPUT;;
        autoremove)     sudo pacman -Qdtq | pacman -Rs -;;
        show)           padman -Qi $INPUT;;
        clean)          sudo pacman -Sc;;
        autoclean)      sudo pacman -Sc;;
        policy)         less /etc/pacman.d/mirrorlist;;
        list)           pacman -Q;;
        listmore)       pacman -Qi;;
        listless)       pacman -Q | wc -l;;
        build)          makepkg -sri;;
        *)
        echo "aptpac: a pacman wrapper with apt syntax";
        echo "no argument/invalid argument - print this help";
        echo "install - installs a package";
        echo "search - searches for a package in the repos";
        echo "remove - removes a package";
        echo "upgrade - upgrades the system fully, refreshing repos and upgrading packages";
        echo "update - only refreshes the repos (bad practice, do not run this without running 'upgrade' immediately after";
        echo "download - only download a package into pacman's cache without installing it";
        echo "autoremove - remove dependencies that are no longer needed (usually should not be needed as 'remove' should remove dependencies along with the package)";
        echo "show - shows information about the package";
        echo "clean/autoclean - clears pacman's cache";
        echo "policy - prints mirrorlist";
        echo "list - lists all installed packages";
        echo "listmore - lists all installed packages with all info";
        echo "listless - lists how many packages are installed";
        echo "build - builds package from PKGBUILD";
esac
